spring.application.name=estacao
spring.datasource.url=jdbc:postgresql://localhost:5432/estacao
spring.datasource.username=postgres
spring.datasource.password=123
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jackson.deserialization.fail-on-unknown-properties=true
